using System.Diagnostics.CodeAnalysis;
using System.Xml;
using Eto.Forms;
using GH_IO.Serialization;
using Grasshopper.Kernel.Special;
using Grasshopper.Kernel.Types;

namespace Robots.Grasshopper;

public class LibraryParam : GH_ValueList
{
    // static 

    internal static bool IsConnected(GH_Component component, [NotNullWhen(true)] out LibraryParam? libraryParam)
    {
        var sources = component.Params.First().Sources;
        libraryParam = sources.OfType<LibraryParam>().FirstOrDefault();
        return libraryParam is not null;
    }

    internal static bool CreateIfEmpty(GH_Document document, GH_Component component, ElementType type, string? selected = null)
    {
        var inputParam = component.Params.First();

        if (inputParam.SourceCount > 0)
            return false;

        var libraryParam = new LibraryParam
        {
            _type = type
        };

        if (selected is not null)
        {
            var selectedItem = new GH_ValueListItem(selected, $"\"{selected}\"")
            {
                Selected = true
            };

            libraryParam.ListItems.Add(selectedItem);
        }

        libraryParam.Update();
        ValueListUtil.AddNearComponent(document, component, inputParam, libraryParam, -240, -21);
        return true;
    }

    public LibraryParam() : base()
    {
        CreateAttributes();
        ListItems.Clear();
    }

    // instance

    ElementType _type;
    public override string Name => "Robots Library";
    public override string Description
    {
        get => "List generated by a Load Robot System, Load Tool, or Load Frame component. Refresh this component to update the list.";
        set => base.Description = value;
    }
    public override Guid ComponentGuid => new("{5DD377EC-F6AF-43F8-8E92-FC6669013E61}");
    public override GH_Exposure Exposure => GH_Exposure.hidden;

    public override void AppendAdditionalMenuItems(System.Windows.Forms.ToolStripDropDown menu)
    {
        menu.Items.Clear();
        _ = Menu_AppendItem(menu, "Refresh", (s, e) => UpdateAndExpire(), Util.GetIcon(nameof(RobotSystemParameter)));
        _ = Menu_AppendSeparator(menu);
    }

    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        Update();
    }

    public override bool Write(GH_IWriter writer)
    {
        writer.SetInt32("Type", (int)_type);
        return base.Write(writer);
    }

    public override bool Read(GH_IReader reader)
    {
        _type = (ElementType)reader.GetInt32("Type");

        if (!Enum.IsDefined(_type))
            throw new InvalidOperationException("Robots library type is invalid.");

        return base.Read(reader);
    }

    internal void UpdateAndExpire()
    {
        Update();
        ExpireSolution(true);
    }

    void Update()
    {
        var selected = (SelectedItems.FirstOrDefault()?.Value as GH_String)?.Value;

        List<string> list;
        try
        {
            list = FileIO.List(_type);
        }
        catch (Exception e)
        {
            var message = e is XmlException ex
                ? $"Invalid XML syntax in \"{Path.GetFileName(ex.SourceUri)}\"."
                : e.Message;

            _ = MessageBox.Show($"Error loading the Robot library\n\n{message}", MessageBoxType.Error);
            list = new List<string>(1);
        }

        if (list.SequenceEqual(ListItems.Select(i => ((GH_String)i.Value).Value)))
            return;

        ListItems.Clear();

        int selectedIndex = 0;

        if (selected is not null)
        {
            selectedIndex = list.FindIndex(n => n.Equals(selected, StringComparison.OrdinalIgnoreCase));

            if (selectedIndex == -1)
            {
                ListItems.Add(new($"{selected} (missing)", $"\"{selected}\""));
                selectedIndex = 0;
            }
        }

        foreach (string name in list)
            ListItems.Add(new(name, $"\"{name}\""));

        if (ListItems.Count > 0)
            ListItems[Math.Min(selectedIndex, ListItems.Count - 1)].Selected = true;
    }
}
