name: 🐞 Bug
description: File a bug
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue or discussion already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: robotsVersion
    attributes:
      label: What Robots version are you using?
      description: You can find the version number using the _PackageManager command. Please check if the bug exists on the latest version.
      placeholder: "1.0.1"
    validations:
      required: true
  - type: dropdown
    id: rhinoVersion
    attributes:
      label: What Rhino version are you using?
      description: Only Rhino 7 and 8 for Windows and MacOS are supported.
      options:
        - Rhino 7 for Windows
        - Rhino 7 for MacOS
        - Rhino 8 for Windows
        - Rhino 8 for MacOS
        - Other
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Links, references, or anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
