name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commands:
        description: 'Commands'
        required: true
        default: '--no-publish'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: dotnet run --project "build/Robots.Build/Robots.Build.csproj" ${{ github.event_name == 'push' && '--publish' || github.event.inputs.commands }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
